import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('training feedback redesign', () => {
  it('uses the standard decorated shell and data-driven body and trend views', () => {
    const page = readFileSync(resolve('src/uni-app/pages/training/feedback.vue'), 'utf8')
    const bodyMap = readFileSync(resolve('src/components/training/TrainingFeedbackBodyMap.vue'), 'utf8')
    const actionCard = readFileSync(resolve('src/components/training/TrainingFeedbackActionCard.vue'), 'utf8')
    const trendChart = readFileSync(resolve('src/components/training/TrainingFeedbackTrendChart.vue'), 'utf8')

    expect(page).toContain('UniTrainingPageShell')
    expect(page).toContain('show-decorations')
    expect(page).toContain('TrainingFeedbackBodyMap')
    expect(page).toContain('TrainingFeedbackTrendChart')
    expect(page).toContain('TrainingFeedbackActionCard')
    expect(page).toContain("mockMode.value || store.state.profile.gender === '女' ? '女' : '男'")
    expect(page).toContain(':gender="feedbackGender"')
    expect(page).toContain('actionResults')
    expect(bodyMap).toContain('CDN_IMAGE_URLS.trainingFeedbackBodyMap')
    expect(bodyMap).toContain('CDN_IMAGE_URLS.trainingFeedbackBodyMapFemale')
    expect(bodyMap).toContain('props.gender ?? studentStore.state.profile.gender')
    expect(bodyMap).toContain(".filter(angle => anglePositions[angle.key])")
    expect(bodyMap).toContain('body-map__connectors')
    expect(bodyMap).toContain('type="2d"')
    expect(bodyMap).toContain("fields({ node: true, size: true }")
    expect(bodyMap).not.toContain('createCanvasContext')
    expect(bodyMap).toContain('context.lineTo(targetX, targetY)')
    expect(bodyMap).toContain("region: 'upper'")
    expect(bodyMap).toContain("region: 'core'")
    expect(bodyMap).toContain("region: 'lower'")
    expect(bodyMap).toContain('startsOnLeft ? 52 : -52')
    expect(bodyMap).toContain("targetY: 38")
    expect(bodyMap).toContain("targetY: 50")
    expect(bodyMap).toContain("targetY: 60")
    expect(bodyMap).toContain("angle.key === 'torso_rotation' ? '躯干'")
    expect(trendChart).toContain('for (const score of [0, 25, 50, 75, 100])')
    expect(trendChart).toContain('String(Math.round(score))')
    expect(trendChart).toContain('right: 30')
    expect(trendChart).toContain('left: 30')
    expect(trendChart).toContain('type="2d"')
    expect(trendChart).toContain("fields({ node: true, size: true }")
    expect(trendChart).not.toContain('createCanvasContext')
    expect(actionCard).toContain('本动作得分趋势')
    expect(actionCard).not.toContain('个角度参与评分')
    expect(actionCard).not.toContain('0—100')
    expect(actionCard).toContain('margin-right: 12rpx')
    expect(page).not.toContain('Mock 测试数据')
    expect(page).not.toContain('Mock 训练已完成')
    expect(page).not.toContain('以下为模拟训练结果')
    expect(page).not.toContain('点击展开')
    expect(page).toContain('.feedback-page__footer-actions { gap: 30rpx;')
    expect(page).toContain('background: #ff8b8b')
    expect(page).toContain('color: #ffffff')
    expect(page).toContain('scroll-content')
    expect(page).toContain('套组总分')
    expect(page).not.toContain('质量得分')
    expect(page).toContain('line-height: 1;')
    expect(page).toContain('show-navigation')
  })

  it('replaces the camera guide drawing with the generated transparent asset', () => {
    const panel = readFileSync(resolve('src/subpackages/training/components/VisualTrainingPanel.vue'), 'utf8')
    expect(panel).toContain(':src="CDN_IMAGE_URLS.cameraPositionGuide"')
    expect(panel).not.toContain('visual-session__guide-torso')
    expect(panel).not.toContain('visual-session__guide-arm')
    expect(panel).not.toContain('visual-session__guide-leg')
  })
})
