import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('visual workout session wiring', () => {
  it('drives sequential arrangement items without touching pose recognition', () => {
    const sessionSource = readFileSync(
      resolve(process.cwd(), 'src/uni-app/composables/useVisualTrainingSession.ts'),
      'utf8'
    )
    const pageSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/visual-session.vue'),
      'utf8'
    )
    const panelSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/components/VisualTrainingPanel.vue'),
      'utf8'
    )

    expect(sessionSource).toContain('loadVisualExerciseArrangement')
    expect(sessionSource).toContain('trainingVideoCache.prefetch(sourceUrl)')
    expect(sessionSource).toContain('await restoreCachedVideo(0)')
    expect(sessionSource).toContain('scheduleVideoPrefetch(0)')
    expect(sessionSource).toContain('void prefetchVideoWindow(itemIndex)')
    expect(sessionSource).not.toContain('await prefetchVideoWindow(0, true)')
    expect(sessionSource).toContain('async function prefetchVideoWindow')
    expect(sessionSource).toContain('async function restoreCachedVideo')
    expect(sessionSource).toContain('prefetchVideoWindow(activeItemIndex.value)')
    expect(sessionSource).toContain('trainingVideoCache.evict(sourceUrl)')
    expect(sessionSource).toContain('const activeItemIndex = shallowRef(0)')
    expect(sessionSource).toContain("const phaseKind = shallowRef<VisualWorkoutPhaseKind>('preview')")
    expect(sessionSource).toContain('phaseRemainingSeconds.value = initialPreviewDurationSeconds')
    expect(sessionSource).toContain('const trainingStarted = shallowRef(false)')
    expect(sessionSource).toContain('const startCountdown = shallowRef(0)')
    expect(sessionSource).toContain('function startTraining()')
    expect(sessionSource).toContain('initialStartCountdownSeconds')
    expect(sessionSource).toContain('startCountdownTimer = setInterval')
    expect(sessionSource).toContain("phaseKind.value = 'rest'")
    expect(sessionSource).toContain("phaseKind.value = 'demonstration'")
    expect(sessionSource).toContain("phaseKind.value = 'countdown'")
    expect(sessionSource).toContain('function beginDemonstration()')
    expect(sessionSource).toContain('function beginStartCue()')
    expect(sessionSource).toContain("if (phaseKind.value === 'rest' || phaseKind.value === 'countdown') return")
    expect(sessionSource).toContain('activeItemIndex.value += 1')
    expect(sessionSource).toContain('beginRestOrNextItem')
    expect(sessionSource).toContain('void finishSession()')
    expect(sessionSource).toContain('function togglePlayback()')
    expect(sessionSource).toContain('/pages/training/short-questionnaire?sessionId=')
    expect(sessionSource).not.toContain('/pages/training/feedback?sessionId=')
    expect(sessionSource).toContain('const workoutState = computed')
    expect(sessionSource).toContain('const workoutTimelineReady = computed')
    expect(sessionSource).toContain("const playbackState = shallowRef<VisualTrainingPlaybackState>('idle')")
    expect(sessionSource).toContain('videoEvent.detail?.duration')
    expect(pageSource).toContain(':workout-state="session.workoutState.value"')
    expect(pageSource).toContain(':video-autoplay="session.videoAutoplay.value"')
    expect(pageSource).toContain(':training-started="session.trainingStarted.value"')
    expect(pageSource).toContain(':start-countdown="session.startCountdown.value"')
    expect(pageSource).toContain('@start-training="session.startTraining"')
    expect(pageSource).toContain(':phase-kind="session.phaseKind.value"')
    expect(pageSource).toContain('@video-play="session.handleVideoPlay"')
    expect(pageSource).toContain('@video-pause="session.handleVideoPause"')
    expect(pageSource).toContain('@toggle-playback="session.togglePlayback"')
    expect(pageSource).toContain('uni.setNavigationBarTitle')
    expect(pageSource).toContain("title: videoTitle || '可视化训练'")
    expect(panelSource).toContain("import WorkoutTimeline from './WorkoutTimeline.vue'")
    expect(panelSource).toContain(':state="workoutState"')
    expect(panelSource).toContain(':autoplay="videoAutoplay"')
    expect(panelSource).toContain(':loop="phaseKind !== \'demonstration\'"')
    expect(panelSource).toContain('visual-session__demonstration-label')
    expect(panelSource).toContain("phaseKind !== 'rest' && phaseKind !== 'countdown'")
    expect(panelSource).toContain('visual-session__phase-overlay')
    expect(panelSource).toContain('visual-session__rest-overlay')
    expect(panelSource).toContain(':controls="false"')
    expect(panelSource).toContain(':show-center-play-btn="false"')
    expect(panelSource).toContain('visual-session__playback-control')
    expect(panelSource).toContain('visual-session__position-guide')
    expect(panelSource).not.toContain('完成训练')
    expect(panelSource).toContain('visual-session__active-timer')
    expect(panelSource).toContain('visual-session__start-overlay')
    expect(panelSource).toContain('开始训练')
    expect(panelSource).toContain('即将开始')
    expect(panelSource).toContain('workoutTimelineReady')
    expect(panelSource).not.toContain('visual-session__header')
    expect(panelSource).not.toContain('visual-session__title-icon')
    expect(panelSource).not.toContain('visual-session__status')
    expect(panelSource).not.toContain("return '待开始'")
    expect(panelSource).toContain(':on-result="result => emit(\'poseResult\', result)"')
    expect(panelSource).toContain(':on-stats="stats => emit(\'poseStats\', stats)"')
  })
})
