import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('visual workout session wiring', () => {
  it('drives sequential arrangement items without touching pose recognition', () => {
    const sessionSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/composables/useVisualTrainingSession.ts'),
      'utf8'
    )
    const pageSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/visual-session.vue'),
      'utf8'
    )
    const panelSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/components/VisualTrainingPanel.vue'),
      'utf8'
    )

    expect(sessionSource).toContain('loadVisualExerciseArrangement')
    expect(sessionSource).toContain('trainingVideoCache.prefetch(sourceUrl)')
    expect(sessionSource).toContain("phaseKind.value === 'active' || phaseKind.value === 'demonstration'")
    expect(sessionSource).toContain('await restoreCachedVideo(0)')
    expect(sessionSource).toContain('scheduleVideoPrefetch(0)')
    expect(sessionSource).toContain('void prefetchVideoWindow(itemIndex)')
    expect(sessionSource).toContain('standardsReadyPromise = preloadActionStandards(nextArrangement, requestId)')
    expect(sessionSource).toContain('function preloadTrainingTts(nextArrangement: ExerciseArrangementDetail)')
    expect(sessionSource).toContain('ttsReadyPromise = preloadTrainingTts(nextArrangement)')
    expect(sessionSource).toContain('await Promise.all([standardsReadyPromise, ttsReadyPromise])')
    expect(sessionSource).not.toContain('await prefetchVideoWindow(0, true)')
    expect(sessionSource).toContain('async function prefetchVideoWindow')
    expect(sessionSource).toContain('async function restoreCachedVideo')
    expect(sessionSource).toContain('prefetchVideoWindow(activeItemIndex.value)')
    expect(sessionSource).toContain('trainingVideoCache.evict(sourceUrl)')
    expect(sessionSource).toContain('const activeItemIndex = shallowRef(0)')
    expect(sessionSource).toContain("const phaseKind = shallowRef<VisualWorkoutPhaseKind>('preview')")
    expect(sessionSource).toContain("const phaseSlot = shallowRef<VisualWorkoutPhaseSlot>('preview')")
    expect(sessionSource).toContain('phaseRemainingSeconds.value = initialPreviewDurationSeconds')
    expect(sessionSource).toContain('const trainingStarted = shallowRef(false)')
    expect(sessionSource).toContain('const startCountdown = shallowRef(0)')
    expect(sessionSource).toContain("type PoseRecognitionStatus = 'idle' | 'preparing' | 'ready' | 'failed'")
    expect(sessionSource).toContain("const recognitionStatus = shallowRef<PoseRecognitionStatus>('idle')")
    expect(sessionSource).toContain("const recognitionReady = computed(() => recognitionStatus.value === 'ready')")
    expect(sessionSource).toContain('function startTraining()')
    const startTrainingSource = sessionSource.slice(
      sessionSource.indexOf('async function startTraining()'),
      sessionSource.indexOf('function beginFirstAction()')
    )
    expect(startTrainingSource).toContain('configureTrainingAudioOutput()')
    expect(sessionSource).toContain('if (!recognitionReady.value)')
    expect(sessionSource).toContain("recognitionStatus.value = 'preparing'")
    expect(sessionSource).toContain("if (stats.status === 'ready')")
    expect(sessionSource).toContain("recognitionStatus.value = 'failed'")
    expect(sessionSource).toContain("phaseKind.value = 'demonstration'")
    expect(sessionSource).toContain("phaseKind.value = 'countdown'")
    expect(sessionSource).toContain("phaseSlot.value = 'pretraining'")
    expect(sessionSource).toContain("phaseSlot.value = 'formal-training'")
    expect(sessionSource).toContain('function beginPretraining()')
    expect(sessionSource).toContain('function beginPretrainingCountdownOrPretraining()')
    expect(sessionSource).toContain('function beginFormalCountdownOrTraining()')
    expect(sessionSource).toContain('function beginFormalTraining()')
    expect(sessionSource).toContain('beginPretrainingCountdownOrPretraining()')
    expect(sessionSource).toContain('beginFormalCountdownOrTraining()')
    expect(sessionSource).not.toContain('function beginPreparation()')
    expect(sessionSource).toContain('setPhaseRemaining(formalDuration)')
    expect(sessionSource).not.toContain("phaseKind.value === 'active' && phaseRemainingSeconds.value === 3")
    expect(sessionSource).toContain('buildTrainingAudioPlan')
    expect(sessionSource).toContain('resolveTrainingAudioPhasePlan')
    expect(sessionSource).not.toContain('countdownDurationSeconds:')
    expect(sessionSource).toContain('ttsPlayer.preload(trainingAudioPlan.speechAudioUrls)')
    expect(sessionSource).toContain('function startConfiguredMediaGuidance(elapsedSeconds = 0)')
    expect(sessionSource).toContain('function startConfiguredPhaseClock()')
    expect(sessionSource).toContain('function startConfiguredMediaPhase()')
    expect(sessionSource).toContain('startConfiguredMediaGuidance()')
    expect(sessionSource).toContain('startConfiguredPhaseClock()')
    expect(sessionSource).toContain('ttsPlayer.schedule(cues)')
    expect(sessionSource).toContain('currentTime > 0')
    expect(sessionSource).toContain('activeItem.value?.pretraining_countdown_duration')
    expect(sessionSource).toContain('activeItem.value?.pretraining_mode')
    expect(sessionSource).toContain('resolvePretrainingDuration(activeItem.value)')
    expect(sessionSource).toContain('The configured deadline is authoritative')
    expect(sessionSource).not.toContain('hasReachedConfiguredDuration')
    expect(sessionSource).toContain("pretrainingMode === 'FIRST_FRAME'")
    expect(sessionSource).toContain('startPhaseTimer(finishPretraining)')
    expect(sessionSource).toContain('activeItem.value?.formal_countdown_duration')
    expect(sessionSource).toContain('const workoutTimeline = computed(() => buildVisualWorkoutTimeline(arrangement.value?.items ?? []))')
    expect(sessionSource).toContain('function continueAfterModuleAudio')
    expect(sessionSource).toContain('ttsPlayer.waitForIdle()')
    expect(sessionSource).toContain('const trainingSoundscape = createTrainingSoundscape(')
    // The shared Web Audio clock is created lazily inside the start gesture,
    // gated by the one-switch rollback constant.
    expect(sessionSource).toContain('const trainingWebAudioClockEnabled = true')
    expect(sessionSource).toContain('const trainingWebAudioTtsEnabled = true')
    expect(sessionSource).toContain(
      'trainingWebAudioClockEnabled ? undefined : () => undefined'
    )
    expect(sessionSource).toContain('trainingWebAudioTtsEnabled ? sharedWebAudioRuntime : null')
    expect(sessionSource).toContain('trainingAudioClock.ensureContext()')
    expect(sessionSource).toContain('trainingAudioClock.rebuildContext()')
    expect(sessionSource).toContain('isContextHealthy: () => trainingAudioClock.isContextHealthy()')
    expect(sessionSource).toContain('scheduleAudioClockRecovery()')
    expect(sessionSource).toContain('onAudioInterruptionBegin?.(handleAudioInterruptionBegin)')
    // Interruption events must never suspend the whole session: the begin
    // event can fire spuriously on the first beat and the end event is not
    // guaranteed, so only the audio stack pauses and a watchdog resumes it.
    expect(sessionSource).toContain('function suspendTrainingAudio()')
    expect(sessionSource).toContain('if (disposed || !trainingStarted.value || sessionSuspended || sessionStopping) return')
    expect(sessionSource).toContain('interruption end event lost; resuming audio')
    expect(sessionSource).not.toContain('function handleAudioInterruptionBegin() {\n    suspendSession()')
    expect(sessionSource).toContain('return trainingAudioClock.nowMs()')
    expect(sessionSource).toContain("phaseKind.value === 'demonstration' ? 'pretraining' : 'formal'")
    expect(sessionSource).toContain('trainingSoundscape.suspend()')
    expect(sessionSource).toContain('trainingSoundscape.stop()')
    expect(sessionSource).toContain('trainingSoundscape.finish(isLastItem)')
    const soundscapeSource = readFileSync(
      resolve(process.cwd(), 'src/uni-app/platform/trainingSoundscape.ts'),
      'utf8'
    )
    expect(soundscapeSource).toContain('https://cdn.sysusports.cn/training-tts/sounds/formal-second.mp3')
    expect(soundscapeSource).toContain('https://cdn.sysusports.cn/training-tts/sounds/formal-boundary.mp3')
    expect(soundscapeSource).toContain('function startTrack(')
    expect(soundscapeSource).toContain('buildTrainingSoundEffectTrack')
    expect(soundscapeSource).toContain('createAnchoredTimelineScheduler')
    expect(soundscapeSource).not.toContain('setInterval(emitNextPulse, 1000)')
    expect(sessionSource).toContain('trainingSoundscape.preload()')
    expect(sessionSource).toContain('const completionAudio = ttsPlayer.enqueue(formalCompletionAudioUrls)')
    expect(sessionSource).toContain('finishSessionAfterPlayback(Promise.all([')
    expect(sessionSource).toContain('ttsPlayer.reset()')
    expect(sessionSource).not.toContain('function syncDemonstrationGuidance(currentTime: number)')
    expect(sessionSource).toContain('return finishSessionAfterPlayback()')
    expect(sessionSource).toContain('async function finishSessionAfterPlayback(completionAudio?: Promise<void>)')
    expect(sessionSource).toContain('await completionAudio')
    expect(sessionSource).toContain('function beginFirstAction()')
    expect(sessionSource).not.toContain('activeStandard()?.tts_cues')
    expect(sessionSource).not.toContain('transition_audio_urls')
    expect(sessionSource).not.toContain('countdown_audio_urls')
    const demonstrationSource = sessionSource.slice(
      sessionSource.indexOf('function beginPretraining()'),
      sessionSource.indexOf('function startTraining()')
    )
    expect(sessionSource).not.toContain("resolveTrainingPhaseTtsCues(completedItem, 'REST'")
    expect(sessionSource).toContain("if (phaseKind.value !== 'active') return")
    expect(sessionSource).toContain('activeItemIndex.value += 1')
    expect(sessionSource).toContain('beginNextItem')
    expect(sessionSource).toContain('async function finishSession()')
    expect(sessionSource).toContain('/pages/training/short-questionnaire?sessionId=')
    expect(sessionSource).toContain('/pages/training/feedback?sessionId=')
    expect(sessionSource).toContain('async function navigateAfterResult()')
    expect(sessionSource).toContain('const workoutState = computed')
    expect(sessionSource).toContain('const workoutTimelineReady = computed')
    expect(sessionSource).toContain("const playbackState = shallowRef<VisualTrainingPlaybackState>('idle')")
    expect(sessionSource).toContain('readVideoEvent(event).detail?.duration')
    expect(pageSource).toContain(':workout-state="session.workoutState.value"')
    expect(pageSource).toContain(':recognition-ready="session.recognitionReady.value"')
    expect(pageSource).toContain(':recognition-status="session.recognitionStatus.value"')
    expect(pageSource).toContain(':video-autoplay="session.videoAutoplay.value"')
    expect(pageSource).toContain(':video-progress-seconds="session.videoProgressSeconds.value"')
    expect(pageSource).not.toContain('pretraining-embedded-countdown-duration')
    expect(pageSource).not.toContain('pretraining-duration-seconds')
    expect(pageSource).toContain(':video-event-token="session.videoEventToken.value"')
    expect(pageSource).toContain(':training-started="session.trainingStarted.value"')
    expect(pageSource).toContain(':preparing-training="session.preparingTraining.value"')
    expect(pageSource).toContain(':training-preparation-label="session.trainingPreparationLabel.value"')
    expect(pageSource).toContain(':start-countdown="session.startCountdown.value"')
    expect(pageSource).toContain('@start-training="session.startTraining"')
    expect(pageSource).toContain(':phase-kind="session.phaseKind.value"')
    expect(pageSource).toContain(':phase-slot="session.phaseSlot.value"')
    expect(pageSource).toContain('@video-play="session.handleVideoPlay"')
    expect(pageSource).toContain('@video-pause="session.handleVideoPause"')
    expect(pageSource).toContain('@video-waiting="session.handleVideoWaiting"')
    expect(pageSource).toContain("return modality.value === 'hiit' ? '自重抗阻跟练' : '传统体育养生跟练'")
    expect(pageSource).toContain('arrangementId.value = Number.isInteger(parsedArrangementId)')
    expect(sessionSource).toContain('options.arrangementId.value ?? undefined')
    expect(sessionSource).toContain('watch([options.modality, options.arrangementId]')
    expect(pageSource).toContain(':page-title="navigationTitle"')
    expect(pageSource).toContain('enableAlertBeforeUnload')
    expect(pageSource).toContain('disableAlertBeforeUnload')
    expect(pageSource).toContain("message: '当前训练尚未完成，退出后本次进度不会保存。'")
    expect(pageSource).toContain('session.trainingStarted.value && !session.videoEnded.value')
    expect(pageSource).toContain('@back="requestExitSession"')
    expect(pageSource).toContain('void requestExitSession()')
    expect(pageSource).toMatch(/async function requestExitSession\(\)[\s\S]*disableNativeExitGuard\(\)[\s\S]*await session\.requestExitSession\(\)[\s\S]*syncNativeExitGuard\(\)/)
    expect(panelSource).toContain("import DemonstrationVideoControls from './DemonstrationVideoControls.vue'")
    expect(panelSource).toContain("import WorkoutTimeline from './WorkoutTimeline.vue'")
    expect(panelSource).toContain(':state="workoutState"')
    expect(panelSource).toContain(':autoplay="videoAutoplay && activeTrainingVideoSlot === \'primary\'"')
    expect(panelSource).toContain(':autoplay="videoAutoplay && activeTrainingVideoSlot === \'buffer\'"')
    expect(panelSource).toContain(':loop="trainingStarted"')
    expect(panelSource).toContain('v-if="!comparisonMode" class="visual-session__info-panel"')
    expect(panelSource).not.toContain('v-if="!comparisonMode && !tutorialMode" class="visual-session__actions"')
    expect(panelSource).not.toContain('先观看完整动作，倒计时后开始跟练')
    expect(panelSource).toContain('const showTutorialDemonstrationControls = computed(() =>')
    expect(panelSource).toContain('visual-session__phase-overlay')
    expect(panelSource).not.toContain('visual-session__rest-overlay')
    expect(panelSource).toContain('预训练示范')
    expect(panelSource).not.toContain('摄像头已就绪，轻触画面开始训练')
    expect(panelSource).toContain('() => !props.tutorialMode')
    expect(panelSource).toContain("&& props.recognitionStatus !== 'failed'")
    expect(panelSource).toContain("emit('startTraining')")
    expect(panelSource).toContain(':controls="true"')
    expect(panelSource).toContain(':controls="false"')
    expect(panelSource).toContain(':show-center-play-btn="true"')
    expect(panelSource).toContain(':show-center-play-btn="false"')
    expect(panelSource).toContain("emit('videoWaiting', wrapVideoEvent($event, 'primary'))")
    expect(panelSource).toContain("emit('videoWaiting', wrapVideoEvent($event, 'buffer'))")
    expect(panelSource).toContain(':enable-progress-gesture="true"')
    expect(panelSource).toContain(':enable-progress-gesture="false"')
    expect(panelSource).toContain('class="visual-session__tutorial-skip"')
    expect(panelSource).not.toContain('visual-session__playback-control')
    expect(panelSource).toContain('visual-session__position-guide')
    expect(panelSource).not.toContain('完成训练')
    expect(panelSource).toContain('visual-session__active-timer')
    expect(panelSource).toContain("if (props.phaseKind === 'countdown')")
    expect(panelSource).not.toContain('pretrainingEmbeddedCountdownDuration')
    expect(panelSource).toContain("phaseKind === 'demonstration'")
    expect(panelSource).toContain('visual-session__start-overlay')
    expect(panelSource).toContain('开始训练')
    expect(panelSource).toContain('即将开始')
    expect(panelSource).toContain('workoutTimelineReady')
    expect(panelSource).not.toContain('visual-session__header')
    expect(panelSource).not.toContain('visual-session__title-icon')
    expect(panelSource).not.toContain('visual-session__status')
    expect(panelSource).not.toContain("return '待开始'")
    expect(panelSource).toContain(':on-result="result => emit(\'poseResult\', result)"')
    expect(panelSource).toContain(':on-stats="stats => emit(\'poseStats\', stats)"')
  })
})
