import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('visual workout session wiring', () => {
  it('drives sequential arrangement items without touching pose recognition', () => {
    const sessionSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/composables/useVisualTrainingSession.ts'),
      'utf8'
    )
    const pageSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/visual-session.vue'),
      'utf8'
    )
    const panelSource = readFileSync(
      resolve(process.cwd(), 'src/subpackages/training/components/VisualTrainingPanel.vue'),
      'utf8'
    )

    expect(sessionSource).toContain('loadVisualExerciseArrangement')
    expect(sessionSource).toContain('trainingVideoCache.prefetch(sourceUrl)')
    expect(sessionSource).toContain('await restoreCachedVideo(0)')
    expect(sessionSource).toContain('scheduleVideoPrefetch(0)')
    expect(sessionSource).toContain('void prefetchVideoWindow(itemIndex)')
    expect(sessionSource).not.toContain('await prefetchVideoWindow(0, true)')
    expect(sessionSource).toContain('async function prefetchVideoWindow')
    expect(sessionSource).toContain('async function restoreCachedVideo')
    expect(sessionSource).toContain('prefetchVideoWindow(activeItemIndex.value)')
    expect(sessionSource).toContain('trainingVideoCache.evict(sourceUrl)')
    expect(sessionSource).toContain('const activeItemIndex = shallowRef(0)')
    expect(sessionSource).toContain("const phaseKind = shallowRef<VisualWorkoutPhaseKind>('preview')")
    expect(sessionSource).toContain("const phaseSlot = shallowRef<VisualWorkoutPhaseSlot>('preview')")
    expect(sessionSource).toContain('phaseRemainingSeconds.value = initialPreviewDurationSeconds')
    expect(sessionSource).toContain('const trainingStarted = shallowRef(false)')
    expect(sessionSource).toContain('const startCountdown = shallowRef(0)')
    expect(sessionSource).toContain("type PoseRecognitionStatus = 'idle' | 'preparing' | 'ready' | 'failed'")
    expect(sessionSource).toContain("const recognitionStatus = shallowRef<PoseRecognitionStatus>('idle')")
    expect(sessionSource).toContain("const recognitionReady = computed(() => recognitionStatus.value === 'ready')")
    expect(sessionSource).toContain('function startTraining()')
    expect(sessionSource).toContain('if (!recognitionReady.value)')
    expect(sessionSource).toContain("recognitionStatus.value = 'preparing'")
    expect(sessionSource).toContain("if (stats.status === 'ready')")
    expect(sessionSource).toContain("recognitionStatus.value = 'failed'")
    expect(sessionSource).toContain("phaseKind.value = 'demonstration'")
    expect(sessionSource).toContain("phaseKind.value = 'countdown'")
    expect(sessionSource).toContain("phaseSlot.value = 'pretraining'")
    expect(sessionSource).toContain("phaseSlot.value = 'formal-training'")
    expect(sessionSource).toContain('function beginPretraining()')
    expect(sessionSource).toContain('function beginPretrainingCountdownOrPretraining()')
    expect(sessionSource).toContain('function beginFormalCountdownOrTraining()')
    expect(sessionSource).toContain('function beginFormalTraining()')
    expect(sessionSource).toContain('beginPretrainingCountdownOrPretraining()')
    expect(sessionSource).toContain('beginFormalCountdownOrTraining()')
    expect(sessionSource).not.toContain('function beginPreparation()')
    expect(sessionSource).toContain('setPhaseRemaining(Math.max(1, activeItem.value?.expected_duration ?? 1))')
    expect(sessionSource).not.toContain("phaseKind.value === 'active' && phaseRemainingSeconds.value === 3")
    expect(sessionSource).toContain('resolveTrainingPhaseTtsCues')
    expect(sessionSource).toContain('resolveTrainingCountdownAudioUrls')
    expect(sessionSource).toContain('function startMediaGuidanceAfterNativePlay()')
    expect(sessionSource).toContain('function syncTimedTrainingGuidance()')
    expect(sessionSource).toContain('activeItem.value?.pretraining_countdown_duration')
    expect(sessionSource).toContain('activeItem.value?.pretraining_mode')
    expect(sessionSource).toContain('resolvePretrainingDuration(activeItem.value)')
    expect(sessionSource).toContain("pretrainingMode === 'FIRST_FRAME'")
    expect(sessionSource).toContain('startPhaseTimer(beginFormalCountdownOrTraining)')
    expect(sessionSource).toContain('activeItem.value?.formal_countdown_duration')
    expect(sessionSource).toContain('const workoutTimeline = computed(() => buildVisualWorkoutTimeline(arrangement.value?.items ?? []))')
    expect(sessionSource).toContain('let pendingEndCue: Promise<void> | undefined')
    expect(sessionSource).toContain('pendingEndCue = ttsPlayer.enqueue(formalCompletionAudioUrls)')
    expect(sessionSource).toContain('ttsPlayer.reset()')
    expect(sessionSource).toContain('function syncDemonstrationGuidance(currentTime: number)')
    expect(sessionSource).toContain('resolveTrainingPhaseDelayedTtsCues(pretrainingGuidanceCues())')
    expect(sessionSource).toContain('void finishSessionAfterPlayback(pendingEndCue)')
    expect(sessionSource).toContain('async function finishSessionAfterPlayback(completionAudio?: Promise<void>)')
    expect(sessionSource).toContain('await completionAudio')
    expect(sessionSource).toContain('function beginFirstAction()')
    expect(sessionSource).not.toContain('activeStandard()?.tts_cues')
    expect(sessionSource).not.toContain('transition_audio_urls')
    expect(sessionSource).not.toContain('countdown_audio_urls')
    const demonstrationSource = sessionSource.slice(
      sessionSource.indexOf('function beginPretraining()'),
      sessionSource.indexOf('function startTraining()')
    )
    expect(sessionSource).not.toContain("resolveTrainingPhaseTtsCues(completedItem, 'REST'")
    expect(sessionSource).toContain("if (phaseKind.value !== 'active') return")
    expect(sessionSource).toContain('activeItemIndex.value += 1')
    expect(sessionSource).toContain('beginNextItem')
    expect(sessionSource).toContain('async function finishSession()')
    expect(sessionSource).toContain('/pages/training/short-questionnaire?sessionId=')
    expect(sessionSource).not.toContain('/pages/training/feedback?sessionId=')
    expect(sessionSource).toContain('const workoutState = computed')
    expect(sessionSource).toContain('const workoutTimelineReady = computed')
    expect(sessionSource).toContain("const playbackState = shallowRef<VisualTrainingPlaybackState>('idle')")
    expect(sessionSource).toContain('readVideoEvent(event).detail?.duration')
    expect(pageSource).toContain(':workout-state="session.workoutState.value"')
    expect(pageSource).toContain(':recognition-ready="session.recognitionReady.value"')
    expect(pageSource).toContain(':recognition-status="session.recognitionStatus.value"')
    expect(pageSource).toContain(':video-autoplay="session.videoAutoplay.value"')
    expect(pageSource).toContain(':video-event-token="session.videoEventToken.value"')
    expect(pageSource).toContain(':training-started="session.trainingStarted.value"')
    expect(pageSource).toContain(':start-countdown="session.startCountdown.value"')
    expect(pageSource).toContain('@start-training="session.startTraining"')
    expect(pageSource).toContain(':phase-kind="session.phaseKind.value"')
    expect(pageSource).toContain(':phase-slot="session.phaseSlot.value"')
    expect(pageSource).toContain('@video-play="session.handleVideoPlay"')
    expect(pageSource).toContain('@video-pause="session.handleVideoPause"')
    expect(pageSource).toContain('@video-waiting="session.handleVideoWaiting"')
    expect(pageSource).toContain('uni.setNavigationBarTitle')
    expect(pageSource).toContain("title: videoTitle || '可视化训练'")
    expect(panelSource).toContain("import DemonstrationVideoControls from './DemonstrationVideoControls.vue'")
    expect(panelSource).toContain("import WorkoutTimeline from './WorkoutTimeline.vue'")
    expect(panelSource).toContain(':state="workoutState"')
    expect(panelSource).toContain(':autoplay="videoAutoplay"')
    expect(panelSource).toContain(':loop="phaseKind !== \'demonstration\'"')
    expect(panelSource).toContain('v-if="!comparisonMode && !tutorialMode" class="visual-session__lower-grid"')
    expect(panelSource).toContain('v-if="!comparisonMode && !tutorialMode" class="visual-session__actions"')
    expect(panelSource).not.toContain('先观看完整动作，倒计时后开始跟练')
    expect(panelSource).toContain('const showTutorialDemonstrationControls = computed(() =>')
    expect(panelSource).toContain('visual-session__phase-overlay')
    expect(panelSource).not.toContain('visual-session__rest-overlay')
    expect(panelSource).toContain('预训练示范')
    expect(panelSource).toContain('开始后按后台模块配置进入训练')
    expect(panelSource).toContain(':controls="true"')
    expect(panelSource).toContain(':controls="false"')
    expect(panelSource).toContain(':show-center-play-btn="true"')
    expect(panelSource).toContain(':show-center-play-btn="false"')
    expect(panelSource).toContain("@waiting=\"emit('videoWaiting', wrapVideoEvent($event))\"")
    expect(panelSource).toContain(':enable-progress-gesture="true"')
    expect(panelSource).toContain(':enable-progress-gesture="false"')
    expect(panelSource).toContain('class="visual-session__tutorial-skip"')
    expect(panelSource).not.toContain('visual-session__playback-control')
    expect(panelSource).toContain('visual-session__position-guide')
    expect(panelSource).not.toContain('完成训练')
    expect(panelSource).toContain('visual-session__active-timer')
    expect(panelSource).toContain("if (props.phaseKind === 'countdown') return props.phaseRemainingSeconds")
    expect(panelSource).toContain("phaseKind === 'demonstration'")
    expect(panelSource).toContain('visual-session__start-overlay')
    expect(panelSource).toContain('开始训练')
    expect(panelSource).toContain('即将开始')
    expect(panelSource).toContain('workoutTimelineReady')
    expect(panelSource).not.toContain('visual-session__header')
    expect(panelSource).not.toContain('visual-session__title-icon')
    expect(panelSource).not.toContain('visual-session__status')
    expect(panelSource).not.toContain("return '待开始'")
    expect(panelSource).toContain(':on-result="result => emit(\'poseResult\', result)"')
    expect(panelSource).toContain(':on-stats="stats => emit(\'poseStats\', stats)"')
  })
})
