/**
 * Build-time script: read BlazePose model files from src/static/models/ and
 * generate a TypeScript module with embedded model data (JSON topology +
 * base64-encoded weight shards).
 *
 * Output: src/uni-app/components/pose/model-data.gen.ts
 *
 * Usage:
 *   npx tsx scripts/generate-model-data.ts
 *
 * Run this whenever model files change.  The generated file is committed to
 * source control so the CI / build pipeline doesn't need to run Kaggle
 * downloads — it just imports the pre-generated data.
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const STATIC_MODELS = path.join(REPO_ROOT, 'src', 'static', 'models');
const OUT_FILE = path.join(
  REPO_ROOT,
  'src',
  'uni-app',
  'components',
  'pose',
  'model-data.gen.ts',
);

interface ModelData {
  topology: object;
  weights: string; // base64 of concatenated .bin files
}

function readJson(filePath: string): object {
  const raw = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(raw);
}

function readBinFiles(dir: string): string {
  // Read all .bin files, sorted by name, concatenate, encode as base64
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.bin'))
    .sort();
  const buffers: Buffer[] = [];
  for (const f of files) {
    buffers.push(fs.readFileSync(path.join(dir, f)));
  }
  return Buffer.concat(buffers).toString('base64');
}

function buildModel(dir: string): ModelData {
  return {
    topology: readJson(path.join(dir, 'model.json')),
    weights: readBinFiles(dir),
  };
}

function generate() {
  const detector = buildModel(path.join(STATIC_MODELS, 'detector'));
  const landmark = buildModel(path.join(STATIC_MODELS, 'landmark_lite'));

  const content = `/**
 * AUTO-GENERATED by scripts/generate-model-data.ts — DO NOT EDIT.
 *
 * Contains embedded BlazePose model data (JSON topology + base64 weight shards)
 * so the WeChat miniprogram can load models via tf.io.fromMemory() without
 * touching the filesystem or network.
 *
 * Regenerate after model updates:
 *   npx tsx scripts/generate-model-data.ts
 */

/* eslint-disable */
/* prettier-ignore */

export const DETECTOR_MODEL_TOPOLOGY: any = ${JSON.stringify(detector.topology)};

export const DETECTOR_WEIGHT_BASE64 =
  '${detector.weights}';

export const LANDMARK_LITE_MODEL_TOPOLOGY: any = ${JSON.stringify(landmark.topology)};

export const LANDMARK_LITE_WEIGHT_BASE64 =
  '${landmark.weights}';
`;

  fs.writeFileSync(OUT_FILE, content, 'utf-8');
  console.log(`✅ Generated ${OUT_FILE}`);
  console.log(
    `   Detector:  topo=${(JSON.stringify(detector.topology).length / 1024).toFixed(0)}KB  weights=${(detector.weights.length / 1024).toFixed(0)}KB (base64)`,
  );
  console.log(
    `   Landmark:  topo=${(JSON.stringify(landmark.topology).length / 1024).toFixed(0)}KB  weights=${(landmark.weights.length / 1024).toFixed(0)}KB (base64)`,
  );
}

generate();
